### ISSUE TITLE
该项目可否用于项目？

### ISSUE THREAD

**Issue by wwhai** [Allenxuxu/stark#2]
之前用了好久micro 感觉很臃肿 想找个精简的 看到大佬这个项目比较符合我的需求，请教下现在处于什么阶段？

**Comment by Allenxuxu** [comment]
> 之前用了好久micro 感觉很臃肿 想找个精简的 看到大佬这个项目比较符合我的需求，请教下现在处于什么阶段？

可以使用，我也是比较喜欢简洁的。这个项目上本质上，就是 register + grpc + http 组合了一下，所以其实没什么复杂的，可以直接用。
我一直想把接口再抽象的优雅一些，但是因为最近工作比较忙，所以一直没怎么花太多时间在这个项目上，后续我时间管理下😂。老哥可以用用看，有问题或建议可以直接提。

**Comment by wwhai** [comment]
> > 之前用了好久micro 感觉很臃肿 想找个精简的 看到大佬这个项目比较符合我的需求，请教下现在处于什么阶段？
> 
> 可以使用，我也是比较喜欢简洁的。这个项目上本质上，就是 register + grpc + http 组合了一下，所以其实没什么复杂的，可以直接用。 我一直想把接口再抽象的优雅一些，但是因为最近工作比较忙，所以一直没怎么花太多时间在这个项目上，后续我时间管理下😂。老哥可以用用看，有问题或建议可以直接提。
-->
好嘞 我试试
